USE lab;
---a
CREATE TABLE Class (
	`id` INT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(50)
);

---b 
INSERT INTO Class (`name`) VALUES ("LALAMAN"), ("SUSMA"), ("BEEKER");

---c 
SELECT * FROM Class;

---d 
START TRANSACTION;

INSERT INTO Class (`name`) VALUES ("NEWMAN");
ROLLBACK; 

INSERT INTO Class (`name`) VALUES ("NEWMAN");
COMMIT;

START TRANSACTION;
SAVEPOINT BeforeEvilEra;
INSERT INTO Class (`name`) VALUES ("EVILERA");
ROLLBACK TO BeforeEvilEra;

COMMIT;